---
postgres_backup_config:
  dir: "{{ postgres_backup_dir | default('/var/backups/postgresql') }}"
  retention_days: "{{ postgres_backup_retention_days | default(14) }}"
  hour: "{{ postgres_backup_hour | default(3) }}"
