"""Build the Changelog nav section from per-sub-repo CHANGELOG.md files.

Two things happen on every build:

- Each sub-repo's own `CHANGELOG.md` (source of truth, full history) is
  copied verbatim into `docs/content/changelog/<name>.md`.
- `docs/content/changelog/index.md` ("Home") is generated from the
  tracked `_intro.md` partial in that same directory, plus a "Latest
  changes" section: for the latest `vX.Y.Z` git tag, the matching
  `## [X.Y.Z]` section from each sub-repo's `CHANGELOG.md` (sub-repos
  with no entry for that version are skipped).

Both kinds of `docs/content/changelog/*.md` output are generated —
do not edit them directly. This is a separate hook from
`sync_readmes.py` (rather than folded into it) since changelog
sync/aggregation is a distinct concern from README syncing, even
though the copy mechanics are similar.
"""

import re
import subprocess
from pathlib import Path

from mkdocs.plugins import get_plugin_logger

log = get_plugin_logger(__name__)

GENERATED_MARKER = (
    "<!-- Auto-generated by docs/hooks/sync_changelogs.py from "
    "{source} — do not edit this file directly. -->"
)

# (path relative to repo root, output filename stem, nav label)
_SUBREPOS = [
    ("apps/barrins_api/CHANGELOG.md", "barrins_api", "Barrin's API"),
    ("apps/barrins_identity/CHANGELOG.md", "barrins_identity", "Barrin's Identity"),
    ("apps/tamiyo_scroll/CHANGELOG.md", "tamiyo_scroll", "Tamiyo Scroll"),
    ("apps/tolaria_news/CHANGELOG.md", "tolaria_news", "Tolaria News"),
    ("docs/CHANGELOG.md", "docs", "Docs"),
    ("ops/my-server/CHANGELOG.md", "ops", "Ops"),
]

# Paths written by this hook during the process's lifetime, so they can
# be removed again in on_shutdown (mkdocs serve keeps rewriting these on
# every reload but never deletes them on its own).
_generated_files: set[Path] = set()


def on_pre_build(config, **kwargs):
    repo_root = Path(config["config_file_path"]).resolve().parent.parent
    changelog_dir = Path(config["docs_dir"]) / "changelog"

    _sync_subrepo_changelogs(repo_root, changelog_dir)
    _write_home_page(repo_root, changelog_dir)


def _sync_subrepo_changelogs(repo_root: Path, changelog_dir: Path) -> None:
    for source_rel, name, _label in _SUBREPOS:
        source = repo_root / source_rel
        if not source.is_file():
            log.info(f"No CHANGELOG.md at {source_rel}, skipping sync.")
            continue

        sections = [
            GENERATED_MARKER.format(source=source_rel),
            "",
            source.read_text(encoding="utf-8").rstrip(),
            "",
        ]
        target = changelog_dir / f"{name}.md"
        target.write_text("\n".join(sections), encoding="utf-8")
        _generated_files.add(target)


def _write_home_page(repo_root: Path, changelog_dir: Path) -> None:
    intro_file = changelog_dir / "_intro.md"
    intro = intro_file.read_text(encoding="utf-8").rstrip() if intro_file.is_file() else ""

    version = _latest_version_tag(repo_root)
    latest_changes = _build_latest_changes_section(repo_root, version)

    sections = [
        GENERATED_MARKER.format(source="changelog/_intro.md + git tags"),
        "",
        "# Changelog",
        "",
        intro,
        "",
        latest_changes,
        "",
    ]
    index_path = changelog_dir / "index.md"
    index_path.write_text("\n".join(sections), encoding="utf-8")
    _generated_files.add(index_path)


def _latest_version_tag(repo_root: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "tag", "--list", "v*", "--sort=-v:refname"],
            cwd=repo_root,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        log.info(f"Could not list git tags ({exc}); Changelog Home will note this.")
        return None
    tags = [t.strip() for t in result.stdout.splitlines() if t.strip()]
    return tags[0].removeprefix("v") if tags else None


def _extract_version_section(changelog_text: str, version: str) -> str | None:
    heading = re.compile(rf"^## \[{re.escape(version)}\].*$", re.MULTILINE)
    match = heading.search(changelog_text)
    if not match:
        return None
    start = match.end()
    next_heading = re.search(r"^## \[", changelog_text[start:], re.MULTILINE)
    end = start + next_heading.start() if next_heading else len(changelog_text)
    return changelog_text[start:end].strip()


def _build_latest_changes_section(repo_root: Path, version: str | None) -> str:
    if version is None:
        return "## Latest changes\n\nNo release has been tagged yet."

    parts = [f"## Latest changes — v{version}", ""]
    found_any = False
    for source_rel, _name, label in _SUBREPOS:
        source = repo_root / source_rel
        if not source.is_file():
            continue
        section = _extract_version_section(
            source.read_text(encoding="utf-8"), version
        )
        if section:
            found_any = True
            parts += [f"### {label}", "", section, ""]

    if not found_any:
        parts.append(f"No sub-repo recorded changes for v{version}.")
    return "\n".join(parts)


def on_shutdown(**kwargs):
    for path in _generated_files:
        if path.is_file():
            path.unlink()
    _generated_files.clear()
