"""Copy READMEs into their mkdocs pages during the build.

Two sources are synced:

- Each app's `apps/<app>/README.md` into every `docs/content/**/<app>/`
  page that already exists (matched by directory name).
- Each Ansible role's `ops/my-server/roles/<role>/README.md` into
  `docs/content/ops/roles/<role>/index.md`, created on demand.

docs/content/**/index.md produced by either sync is generated output — do
not edit it directly. Nav links that need to survive the copy live in a
sibling `_links.md` file (excluded from the built site via `exclude_docs`
in mkdocs.yml) and are appended under a "## See also" section.
"""

from pathlib import Path

from mkdocs.plugins import get_plugin_logger

log = get_plugin_logger(__name__)

GENERATED_MARKER = (
    "<!-- Auto-generated by docs/hooks/sync_readmes.py from "
    "{source} — do not edit this file directly. -->"
)

# Paths written by _write_index during this process's lifetime, so they can
# be removed again in on_shutdown (mkdocs serve keeps rewriting these on
# every reload but never deletes them on its own).
_generated_files: set[Path] = set()

# Directories this hook created (as opposed to ones that already existed,
# e.g. app doc pages with a tracked _links.md). Removed again in
# on_shutdown if left empty.
_created_dirs: set[Path] = set()


def on_pre_build(config, **kwargs):
    repo_root = Path(config["config_file_path"]).resolve().parent.parent
    content_dir = Path(config["docs_dir"])

    _sync_app_readmes(repo_root, content_dir)
    _sync_role_readmes(repo_root, content_dir)


def _sync_app_readmes(repo_root, content_dir):
    apps_dir = repo_root / "apps"
    if not apps_dir.is_dir():
        return

    for app_dir in sorted(p for p in apps_dir.iterdir() if p.is_dir()):
        readme = app_dir / "README.md"
        if not readme.is_file():
            continue

        targets = [p for p in content_dir.rglob(app_dir.name) if p.is_dir()]
        if not targets:
            log.info(f"No docs page for app '{app_dir.name}', skipping README sync.")
            continue

        for target_dir in targets:
            _write_index(f"apps/{app_dir.name}/README.md", readme, target_dir)


def _sync_role_readmes(repo_root, content_dir):
    roles_dir = repo_root / "ops" / "my-server" / "roles"
    if not roles_dir.is_dir():
        return

    roles_root = content_dir / "ops" / "roles"

    for role_dir in sorted(p for p in roles_dir.iterdir() if p.is_dir()):
        readme = role_dir / "README.md"
        if not readme.is_file():
            continue

        target_dir = roles_root / role_dir.name
        if not target_dir.is_dir():
            target_dir.mkdir(parents=True)
            _created_dirs.add(target_dir)

        _write_index(
            f"ops/my-server/roles/{role_dir.name}/README.md", readme, target_dir
        )


def on_shutdown(**kwargs):
    for path in _generated_files:
        if path.is_file():
            path.unlink()
    _generated_files.clear()

    for path in sorted(_created_dirs, reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()
    _created_dirs.clear()


def _write_index(source, readme, target_dir):
    sections = [
        GENERATED_MARKER.format(source=source),
        "",
        readme.read_text(encoding="utf-8").rstrip(),
    ]

    links_file = target_dir / "_links.md"
    if links_file.is_file():
        links = links_file.read_text(encoding="utf-8").strip()
        if links:
            sections += ["", "## See also", "", links]

    sections.append("")
    index_path = target_dir / "index.md"
    index_path.write_text("\n".join(sections), encoding="utf-8")
    _generated_files.add(index_path)
