"""Copy each app's README.md into its mkdocs page during the build.

docs/content/**/<app>/index.md is generated output — do not edit it directly.
Nav links that need to survive the copy live in a sibling `_links.md` file
(excluded from the built site via `exclude_docs` in mkdocs.yml) and are
appended under a "## See also" section.
"""

from pathlib import Path

from mkdocs.plugins import get_plugin_logger

log = get_plugin_logger(__name__)

GENERATED_MARKER = (
    "<!-- Auto-generated by docs/hooks/sync_readmes.py from "
    "apps/{app}/README.md — do not edit this file directly. -->"
)


def on_pre_build(config, **kwargs):
    repo_root = Path(config["config_file_path"]).resolve().parent.parent
    apps_dir = repo_root / "apps"
    content_dir = Path(config["docs_dir"])

    if not apps_dir.is_dir():
        return

    for app_dir in sorted(p for p in apps_dir.iterdir() if p.is_dir()):
        readme = app_dir / "README.md"
        if not readme.is_file():
            continue

        targets = [p for p in content_dir.rglob(app_dir.name) if p.is_dir()]
        if not targets:
            log.info(f"No docs page for app '{app_dir.name}', skipping README sync.")
            continue

        for target_dir in targets:
            _write_index(app_dir.name, readme, target_dir)


def _write_index(app_name, readme, target_dir):
    sections = [
        GENERATED_MARKER.format(app=app_name),
        "",
        readme.read_text(encoding="utf-8").rstrip(),
    ]

    links_file = target_dir / "_links.md"
    if links_file.is_file():
        links = links_file.read_text(encoding="utf-8").strip()
        if links:
            sections += ["", "## See also", "", links]

    sections.append("")
    (target_dir / "index.md").write_text("\n".join(sections), encoding="utf-8")
