"""Copy the Claude Code constitution into its mkdocs page during the build.

`.claude/CLAUDE.md` (the highest-level project guidance Claude Code reads
directly) is the source of truth. It is copied verbatim into
`docs/content/CLAUDE.md` so the constitution is browsable in the generated
documentation site under the "Constitution" nav entry.

docs/content/CLAUDE.md is generated output — do not edit it directly, edit
`.claude/CLAUDE.md` instead.
"""

from pathlib import Path

from mkdocs.plugins import get_plugin_logger

log = get_plugin_logger(__name__)

GENERATED_MARKER = (
    "<!-- Auto-generated by docs/hooks/sync_constitution.py from "
    "{source} — do not edit this file directly. -->"
)

SOURCE_REL = ".claude/CLAUDE.md"

# Path written by this hook during the process's lifetime, so it can be
# removed again in on_shutdown (mkdocs serve keeps rewriting this on every
# reload but never deletes it on its own).
_generated_file: Path | None = None


def on_pre_build(config, **kwargs):
    global _generated_file

    repo_root = Path(config["config_file_path"]).resolve().parent.parent
    source = repo_root / SOURCE_REL
    if not source.is_file():
        log.info(f"No {SOURCE_REL}, skipping constitution sync.")
        return

    sections = [
        GENERATED_MARKER.format(source=SOURCE_REL),
        "",
        source.read_text(encoding="utf-8").rstrip(),
        "",
    ]
    target = Path(config["docs_dir"]) / "CLAUDE.md"
    target.write_text("\n".join(sections), encoding="utf-8")
    _generated_file = target


def on_shutdown(**kwargs):
    global _generated_file
    if _generated_file is not None and _generated_file.is_file():
        _generated_file.unlink()
    _generated_file = None
