version: 2

updates:
  - package-ecosystem: "uv"
    directories:
      - "/apps/*"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-updates:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directories:
      - "/apps/*"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-updates:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/docs"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-updates:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-updates:
        patterns:
          - "*"
