---
register_ssl_config:
  server_name: "{{ register_ssl_server_name }}"
  contact_name: "{{ username }}@{{ register_ssl_server_name }}"
  site_root: "/home/{{ username }}/projects/{{ register_ssl_server_name }}"
