---
r:
  repo: "{{fb_repo}}"
  git_branch: "{{fb_git_branch | default('main')}}"
  use_release_tag: "{{fb_use_release_tag | default(false)}}"
  release_tag: "{{fb_release_tag | default('')}}"
  server_name: "{{fb_server_name}}"
  app_name: "{{fb_app_name | default(fb_server_name)}}"
  app_root: "/home/{{username}}/projects/{{fb_server_name}}"
  port: "{{fb_port}}"
  entrypoint: "{{fb_entrypoint}}"
  env_vars: "{{fb_env | default({})}}"
  env_file: "{{fb_env_file | default('')}}"
  github_token: "{{fb_github_token | default(github_token)}}"
