---
- hosts: all
  become: true
  gather_facts: false
  vars:
    username: spigushe
  roles:
    - role: setup-packages

- hosts: all
  gather_facts: false
  vars:
    username: spigushe
  roles:
    - role: create-ssh-key
