---
r:
  repo: "{{rf_repo}}"
  git_branch: "{{rf_git_branch | default('main')}}"
  use_release_tag: "{{rf_use_release_tag | default(false)}}"
  release_tag: "{{rf_release_tag | default('')}}"
  server_name: "{{rf_server_name}}"
  app_name: "{{rf_app_name | default(rf_server_name)}}"
  site_root: "/home/{{username}}/projects/{{rf_server_name}}"
  node_version: "{{rf_node_version | default('22')}}"
  package_manager: "{{rf_package_manager | default('npm')}}"
  build_command: "{{rf_build_command | default('npm run build')}}"
  build_dir: "{{rf_build_dir | default('dist')}}"
  build_env: "{{rf_build_env | default({})}}"
  github_token: "{{rf_github_token | default(github_token)}}"
